import { franceMapData } from '@/registry/shadcnmaps/map-data/france'
import { usaMapData } from '@/registry/shadcnmaps/map-data/usa'
// Auto-generated by scripts/build-maps-config.ts — do not edit manually
import type { MapData } from '@/registry/shadcnmaps/types'

export const MAPS: Record<string, { data: MapData; label: string }> = {
  france: { data: franceMapData, label: 'France' },
  usa: { data: usaMapData, label: 'United States' },
}
