import { africaMapData } from '@/registry/shadcnmaps/map-data/africa'
import { alabamaMapData } from '@/registry/shadcnmaps/map-data/alabama'
import { alaskaMapData } from '@/registry/shadcnmaps/map-data/alaska'
import { algeriaMapData } from '@/registry/shadcnmaps/map-data/algeria'
import { angolaMapData } from '@/registry/shadcnmaps/map-data/angola'
import { argentinaMapData } from '@/registry/shadcnmaps/map-data/argentina'
import { arizonaMapData } from '@/registry/shadcnmaps/map-data/arizona'
import { arkansasMapData } from '@/registry/shadcnmaps/map-data/arkansas'
import { asiaMapData } from '@/registry/shadcnmaps/map-data/asia'
import { australiaMapData } from '@/registry/shadcnmaps/map-data/australia'
import { austriaMapData } from '@/registry/shadcnmaps/map-data/austria'
import { azerbaijanMapData } from '@/registry/shadcnmaps/map-data/azerbaijan'
import { bahrainMapData } from '@/registry/shadcnmaps/map-data/bahrain'
import { bangladeshMapData } from '@/registry/shadcnmaps/map-data/bangladesh'
import { belarusMapData } from '@/registry/shadcnmaps/map-data/belarus'
import { belgiumMapData } from '@/registry/shadcnmaps/map-data/belgium'
import { boliviaMapData } from '@/registry/shadcnmaps/map-data/bolivia'
import { brazilMapData } from '@/registry/shadcnmaps/map-data/brazil'
import { bulgariaMapData } from '@/registry/shadcnmaps/map-data/bulgaria'
import { californiaMapData } from '@/registry/shadcnmaps/map-data/california'
import { cameroonMapData } from '@/registry/shadcnmaps/map-data/cameroon'
import { canadaMapData } from '@/registry/shadcnmaps/map-data/canada'
import { caribbeanMapData } from '@/registry/shadcnmaps/map-data/caribbean'
import { centralAmericaMapData } from '@/registry/shadcnmaps/map-data/central-america'
import { chinaMapData } from '@/registry/shadcnmaps/map-data/china'
import { colombiaMapData } from '@/registry/shadcnmaps/map-data/colombia'
import { coloradoMapData } from '@/registry/shadcnmaps/map-data/colorado'
import { connecticutMapData } from '@/registry/shadcnmaps/map-data/connecticut'
import { costaRicaMapData } from '@/registry/shadcnmaps/map-data/costa-rica'
import { coteIvoireMapData } from '@/registry/shadcnmaps/map-data/cote-ivoire'
import { croatiaMapData } from '@/registry/shadcnmaps/map-data/croatia'
import { cubaMapData } from '@/registry/shadcnmaps/map-data/cuba'
import { czechRepublicMapData } from '@/registry/shadcnmaps/map-data/czech-republic'
import { franceMapData } from '@/registry/shadcnmaps/map-data/france'
import { usaMapData } from '@/registry/shadcnmaps/map-data/usa'
import { worldMapData } from '@/registry/shadcnmaps/map-data/world'
// Auto-generated by scripts/build-maps-config.ts — do not edit manually
import type { MapData } from '@/registry/shadcnmaps/types'

export const MAPS: Record<string, { data: MapData; label: string }> = {
  africa: { data: africaMapData, label: 'Africa' },
  alabama: { data: alabamaMapData, label: 'Alabama' },
  alaska: { data: alaskaMapData, label: 'Alaska' },
  algeria: { data: algeriaMapData, label: 'Algeria' },
  angola: { data: angolaMapData, label: 'Angola' },
  argentina: { data: argentinaMapData, label: 'Argentina' },
  arizona: { data: arizonaMapData, label: 'Arizona' },
  arkansas: { data: arkansasMapData, label: 'Arkansas' },
  asia: { data: asiaMapData, label: 'Asia' },
  australia: { data: australiaMapData, label: 'Australia' },
  austria: { data: austriaMapData, label: 'Austria' },
  azerbaijan: { data: azerbaijanMapData, label: 'Azerbaijan' },
  bahrain: { data: bahrainMapData, label: 'Bahrain' },
  bangladesh: { data: bangladeshMapData, label: 'Bangladesh' },
  belarus: { data: belarusMapData, label: 'Belarus' },
  belgium: { data: belgiumMapData, label: 'Belgium' },
  bolivia: { data: boliviaMapData, label: 'Bolivia' },
  brazil: { data: brazilMapData, label: 'Brazil' },
  bulgaria: { data: bulgariaMapData, label: 'Bulgaria' },
  california: { data: californiaMapData, label: 'California' },
  cameroon: { data: cameroonMapData, label: 'Cameroon' },
  canada: { data: canadaMapData, label: 'Canada' },
  caribbean: { data: caribbeanMapData, label: 'Caribbean' },
  'central-america': { data: centralAmericaMapData, label: 'Central America' },
  china: { data: chinaMapData, label: 'China' },
  colombia: { data: colombiaMapData, label: 'Colombia' },
  colorado: { data: coloradoMapData, label: 'Colorado' },
  connecticut: { data: connecticutMapData, label: 'Connecticut' },
  'costa-rica': { data: costaRicaMapData, label: 'Costa Rica' },
  'cote-ivoire': { data: coteIvoireMapData, label: "Côte d'Ivoire" },
  croatia: { data: croatiaMapData, label: 'Croatia' },
  cuba: { data: cubaMapData, label: 'Cuba' },
  'czech-republic': { data: czechRepublicMapData, label: 'Czech Republic' },
  france: { data: franceMapData, label: 'France' },
  usa: { data: usaMapData, label: 'United States' },
  world: { data: worldMapData, label: 'World' },
}
