export interface NavItem {
  title: string
  href: string
}

export interface NavSubGroup {
  title: string
  items: NavItem[]
}

export interface NavSection {
  title: string
  href?: string
  hideLabel?: boolean
  items?: NavItem[]
  groups?: NavSubGroup[]
}

export const navigation: NavSection[] = [
  {
    title: 'Documentation',
    hideLabel: true,
    items: [
      { title: 'Getting Started', href: '/overview/getting-started' },
      { title: 'Theming', href: '/overview/theming' },
      { title: 'API Reference', href: '/overview/api-reference' },
      { title: 'LLMs', href: '/overview/llms' },
      { title: 'Zoom & Pan', href: '/overview/zoom-pan' },
      { title: 'Marker Generator', href: '/tools/marker-generator' },
      { title: 'Search Maps', href: '/maps' },
    ],
  },
  {
    title: 'Maps',
    href: '/maps',
    groups: [
      {
        title: 'Regions & Continents',
        items: [
          { title: 'Africa', href: '/maps/africa' },
          { title: 'Asia', href: '/maps/asia' },
          { title: 'Caribbean', href: '/maps/caribbean' },
          { title: 'Central America', href: '/maps/central-america' },
          { title: 'Continents', href: '/maps/continents' },
          { title: 'Europe', href: '/maps/europe' },
          { title: 'European Union', href: '/maps/european-union' },
          { title: 'Middle East', href: '/maps/middle-east' },
          { title: 'North Africa', href: '/maps/north-africa' },
          { title: 'North America', href: '/maps/north-america' },
          { title: 'South America', href: '/maps/south-america' },
          { title: 'World', href: '/maps/world' },
          {
            title: 'World (Jammu & Kashmir)',
            href: '/maps/world-jammu-kashmir',
          },
        ],
      },
      {
        title: 'Countries',
        items: [
          { title: 'Algeria', href: '/maps/algeria' },
          { title: 'Angola', href: '/maps/angola' },
          { title: 'Argentina', href: '/maps/argentina' },
          { title: 'Australia', href: '/maps/australia' },
          { title: 'Austria', href: '/maps/austria' },
          { title: 'Azerbaijan', href: '/maps/azerbaijan' },
          { title: 'Bahrain', href: '/maps/bahrain' },
          { title: 'Bangladesh', href: '/maps/bangladesh' },
          { title: 'Belarus', href: '/maps/belarus' },
          { title: 'Belgium', href: '/maps/belgium' },
          { title: 'Bolivia', href: '/maps/bolivia' },
          { title: 'Brazil', href: '/maps/brazil' },
          { title: 'Bulgaria', href: '/maps/bulgaria' },
          { title: 'Cameroon', href: '/maps/cameroon' },
          { title: 'Canada', href: '/maps/canada' },
          { title: 'China', href: '/maps/china' },
          { title: 'Colombia', href: '/maps/colombia' },
          { title: 'Costa Rica', href: '/maps/costa-rica' },
          { title: 'Croatia', href: '/maps/croatia' },
          { title: 'Cuba', href: '/maps/cuba' },
          { title: 'Czech Republic', href: '/maps/czech-republic' },
          {
            title: 'Democratic Republic of the Congo',
            href: '/maps/democratic-republic-congo',
          },
          { title: 'Denmark', href: '/maps/denmark' },
          { title: 'Dominican Republic', href: '/maps/dominican-republic' },
          { title: 'Ecuador', href: '/maps/ecuador' },
          { title: 'Egypt', href: '/maps/egypt' },
          { title: 'El Salvador', href: '/maps/el-salvador' },
          { title: 'Estonia', href: '/maps/estonia' },
          { title: 'Ethiopia', href: '/maps/ethiopia' },
          { title: 'Finland', href: '/maps/finland' },
          { title: 'France', href: '/maps/france' },
          { title: 'Germany', href: '/maps/germany' },
          { title: 'Ghana', href: '/maps/ghana' },
          { title: 'Greece', href: '/maps/greece' },
          { title: 'Guatemala', href: '/maps/guatemala' },
          { title: 'Honduras', href: '/maps/honduras' },
          { title: 'Hungary', href: '/maps/hungary' },
          { title: 'India', href: '/maps/india' },
          { title: 'Indonesia', href: '/maps/indonesia' },
          { title: 'Iran', href: '/maps/iran' },
          { title: 'Iraq', href: '/maps/iraq' },
          { title: 'Ireland', href: '/maps/ireland' },
          { title: 'Israel', href: '/maps/israel' },
          { title: 'Italy', href: '/maps/italy' },
          { title: 'Japan', href: '/maps/japan' },
          { title: 'Jordan', href: '/maps/jordan' },
          { title: 'Kazakhstan', href: '/maps/kazakhstan' },
          { title: 'Kenya', href: '/maps/kenya' },
          { title: 'Kuwait', href: '/maps/kuwait' },
          { title: 'Latvia', href: '/maps/latvia' },
          { title: 'Lebanon', href: '/maps/lebanon' },
          { title: 'Libya', href: '/maps/libya' },
          { title: 'Lithuania', href: '/maps/lithuania' },
          { title: 'Luxembourg', href: '/maps/luxembourg' },
          { title: 'Macau', href: '/maps/macau' },
          { title: 'Malaysia', href: '/maps/malaysia' },
          { title: 'Mexico', href: '/maps/mexico' },
          { title: 'Monaco', href: '/maps/monaco' },
          { title: 'Morocco', href: '/maps/morocco' },
          { title: 'Myanmar', href: '/maps/myanmar' },
          { title: 'Nepal', href: '/maps/nepal' },
          { title: 'Netherlands', href: '/maps/netherlands' },
          { title: 'New Zealand', href: '/maps/new-zealand' },
          { title: 'Nigeria', href: '/maps/nigeria' },
          { title: 'Norway', href: '/maps/norway' },
          { title: 'Oman', href: '/maps/oman' },
          { title: 'Pakistan', href: '/maps/pakistan' },
          { title: 'Panama', href: '/maps/panama' },
          { title: 'Paraguay', href: '/maps/paraguay' },
          { title: 'Peru', href: '/maps/peru' },
          { title: 'Philippines', href: '/maps/philippines' },
          { title: 'Poland', href: '/maps/poland' },
          { title: 'Portugal', href: '/maps/portugal' },
          { title: 'Puerto Rico', href: '/maps/puerto-rico' },
          { title: 'Qatar', href: '/maps/qatar' },
          { title: 'Romania', href: '/maps/romania' },
          { title: 'Russia', href: '/maps/russia' },
          { title: 'Saudi Arabia', href: '/maps/saudi-arabia' },
          { title: 'Serbia', href: '/maps/serbia' },
          { title: 'Singapore', href: '/maps/singapore' },
          { title: 'Slovakia', href: '/maps/slovakia' },
          { title: 'Slovenia', href: '/maps/slovenia' },
          { title: 'South Africa', href: '/maps/south-africa' },
          { title: 'South Korea', href: '/maps/south-korea' },
          { title: 'Spain', href: '/maps/spain' },
          { title: 'Sri Lanka', href: '/maps/sri-lanka' },
          { title: 'Sudan', href: '/maps/sudan' },
          { title: 'Sweden', href: '/maps/sweden' },
          { title: 'Switzerland', href: '/maps/switzerland' },
          { title: 'Syria', href: '/maps/syria' },
          { title: 'Taiwan', href: '/maps/taiwan' },
          { title: 'Tanzania', href: '/maps/tanzania' },
          { title: 'Thailand', href: '/maps/thailand' },
          { title: 'Trinidad and Tobago', href: '/maps/trinidad-and-tobago' },
          { title: 'Tunisia', href: '/maps/tunisia' },
          { title: 'Turkey', href: '/maps/turkey' },
          { title: 'Turkmenistan', href: '/maps/turkmenistan' },
          { title: 'Uganda', href: '/maps/uganda' },
          { title: 'Ukraine', href: '/maps/ukraine' },
          { title: 'United Arab Emirates', href: '/maps/uae' },
          { title: 'United Kingdom', href: '/maps/uk' },
          { title: 'Uruguay', href: '/maps/uruguay' },
          { title: 'USA', href: '/maps/usa' },
          { title: 'Uzbekistan', href: '/maps/uzbekistan' },
          { title: 'Venezuela', href: '/maps/venezuela' },
          { title: 'Vietnam', href: '/maps/vietnam' },
          { title: 'Yemen', href: '/maps/yemen' },
          { title: 'Zambia', href: '/maps/zambia' },
          { title: 'Zimbabwe', href: '/maps/zimbabwe' },
        ],
      },
      {
        title: 'US States',
        items: [
          { title: 'Alabama', href: '/maps/alabama' },
          { title: 'Alaska', href: '/maps/alaska' },
          { title: 'Arizona', href: '/maps/arizona' },
          { title: 'Arkansas', href: '/maps/arkansas' },
          { title: 'California', href: '/maps/california' },
          { title: 'Colorado', href: '/maps/colorado' },
          { title: 'Connecticut', href: '/maps/connecticut' },
          { title: 'Delaware', href: '/maps/delaware' },
          { title: 'Florida', href: '/maps/florida' },
          { title: 'Georgia', href: '/maps/georgia' },
          { title: 'Hawaii', href: '/maps/hawaii' },
          { title: 'Idaho', href: '/maps/idaho' },
          { title: 'Illinois', href: '/maps/illinois' },
          { title: 'Indiana', href: '/maps/indiana' },
          { title: 'Iowa', href: '/maps/iowa' },
          { title: 'Kansas', href: '/maps/kansas' },
          { title: 'Kentucky', href: '/maps/kentucky' },
          { title: 'Louisiana', href: '/maps/louisiana' },
          { title: 'Maine', href: '/maps/maine' },
          { title: 'Maryland', href: '/maps/maryland' },
          { title: 'Massachusetts', href: '/maps/massachusetts' },
          { title: 'Michigan', href: '/maps/michigan' },
          { title: 'Minnesota', href: '/maps/minnesota' },
          { title: 'Mississippi', href: '/maps/mississippi' },
          { title: 'Missouri', href: '/maps/missouri' },
          { title: 'Montana', href: '/maps/montana' },
          { title: 'Nebraska', href: '/maps/nebraska' },
          { title: 'Nevada', href: '/maps/nevada' },
          { title: 'New Hampshire', href: '/maps/new-hampshire' },
          { title: 'New Jersey', href: '/maps/new-jersey' },
          { title: 'New Mexico', href: '/maps/new-mexico' },
          { title: 'New York', href: '/maps/new-york' },
          { title: 'North Carolina', href: '/maps/north-carolina' },
          { title: 'North Dakota', href: '/maps/north-dakota' },
          { title: 'Ohio', href: '/maps/ohio' },
          { title: 'Oklahoma', href: '/maps/oklahoma' },
          { title: 'Oregon', href: '/maps/oregon' },
          { title: 'Pennsylvania', href: '/maps/pennsylvania' },
          { title: 'Rhode Island', href: '/maps/rhode-island' },
          { title: 'South Carolina', href: '/maps/south-carolina' },
          { title: 'South Dakota', href: '/maps/south-dakota' },
          { title: 'Tennessee', href: '/maps/tennessee' },
          { title: 'Texas', href: '/maps/texas' },
          { title: 'Utah', href: '/maps/utah' },
          { title: 'Vermont', href: '/maps/vermont' },
          { title: 'Virginia', href: '/maps/virginia' },
          { title: 'Washington', href: '/maps/washington' },
          { title: 'West Virginia', href: '/maps/west-virginia' },
          { title: 'Wisconsin', href: '/maps/wisconsin' },
          { title: 'Wyoming', href: '/maps/wyoming' },
        ],
      },
      {
        title: 'Special',
        items: [
          { title: 'France Départements', href: '/maps/france-departements' },
          { title: 'London Boroughs', href: '/maps/london-boroughs' },
          {
            title: 'New York City Boroughs',
            href: '/maps/new-york-city-boroughs',
          },
          { title: 'Northeast USA', href: '/maps/northeast-usa' },
          { title: 'Palestine & Israel', href: '/maps/palestine-israel' },
          { title: 'USA & Canada', href: '/maps/usa-canada' },
          { title: 'USA Territories', href: '/maps/usa-territories' },
        ],
      },
    ],
  },
  {
    title: 'Examples',
    items: [
      { title: 'Region Click', href: '/examples/region-click' },
      { title: 'Choropleth', href: '/examples/choropleth' },
      { title: 'Markers', href: '/examples/markers' },
      { title: 'Zoom & Pan', href: '/examples/zoom-pan' },
      { title: 'Controlled', href: '/examples/controlled' },
    ],
  },
]
