import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

const MAP_DATA_DIR = resolve(process.cwd(), 'registry/shadcnmaps/map-data')
const OUTPUT = resolve(
  process.cwd(),
  'app/(docs)/tools/marker-generator/maps-config.ts'
)

// Find all map data files (exclude registry.ts)
const files = readdirSync(MAP_DATA_DIR)
  .filter((f) => f.endsWith('.ts') && f !== 'registry.ts')
  .toSorted()

// Extract the export name and id from each file
const maps: { file: string; exportName: string; id: string; name: string }[] =
  []

for (const file of files) {
  const content = readFileSync(resolve(MAP_DATA_DIR, file), 'utf-8')

  // Match: export const usaMapData = {
  const exportMatch = content.match(/export const (\w+MapData)\s*=/)
  if (!exportMatch) continue

  // Match: id: 'usa',
  const idMatch = content.match(/id:\s*'([^']+)'/)
  // Match: name: 'United States',
  const nameMatch = content.match(/name:\s*'([^']+)'/)
  if (!idMatch || !nameMatch) continue

  maps.push({
    file: file.replace('.ts', ''),
    exportName: exportMatch[1],
    id: idMatch[1],
    name: nameMatch[1],
  })
}

// Generate the config file
const imports = maps
  .map(
    (m) =>
      `import { ${m.exportName} } from '@/registry/shadcnmaps/map-data/${m.file}'`
  )
  .join('\n')

const entries = maps
  .map((m) => `  '${m.id}': { data: ${m.exportName}, label: '${m.name}' },`)
  .join('\n')

const output = `// Auto-generated by scripts/build-maps-config.ts — do not edit manually
import type { MapData } from '@/registry/shadcnmaps/types'

${imports}

export const MAPS: Record<string, { data: MapData; label: string }> = {
${entries}
}
`

writeFileSync(OUTPUT, output)
console.log(`✓ Built maps-config with ${maps.length} maps`)
